site_name: TODO (provide site_name in mkdocs.yml)
nav:
  - Home: README.md
  - User Guide: user-guide.md
  - Developer Guide: development.md
  - Deployment Guide: jenkins-cicd.md
  - Release Notes: release-notes.md
