site_name: TODO (provide site name in mkdocs.yml)
theme:
  name: material
nav:
    - User Guide: user-guide.md
    - Developer Guide: development.md
    - Deployment Guide: jenkins-cicd.md
    - Release Notes: release-notes.md
